import json
import requests
import os
from concurrent.futures import ThreadPoolExecutor, as_completed
from threading import Lock

#    过滤器模式 ('whitelist' 或 'blacklist')
#    'blacklist': 处理所有图标，除了 FILTER_LIST 中的。
#    'whitelist': 只处理 FILTER_LIST 中指定的图标。
FILTER_MODE = 'blacklist'

#    过滤器列表 (配合 FILTER_MODE 使用)
FILTER_LIST = [
]

#    名称到显示名称映射表
#    用于将内部名称转换为更美观的显示名称，会应用在 <a> 的 title 和 <img> 的 alt 属性中。
#    格式: "内部名称": "显示名称"
NAME_TO_DISPLAY_NAME_MAP = {
    "aarch64": "AArch64",
    "adonisjs": "AdonisJS",
    "aerospike": "Aerospike",
    "aframe": "A-Frame",
    "aftereffects": "After Effects",
    "akka": "Akka",
    "algolia": "Algolia",
    "almalinux": "AlmaLinux",
    "alpinejs": "Alpine.js",
    "amazonwebservices": "Amazon Web Services",
    "anaconda": "Anaconda",
    "android": "Android",
    "androidstudio": "Android Studio",
    "angular": "Angular",
    "angularjs": "AngularJS",
    "angularmaterial": "Angular Material",
    "ansible": "Ansible",
    "ansys": "Ansys",
    "antdesign": "Ant Design",
    "apache": "Apache",
    "apacheairflow": "Apache Airflow",
    "apachekafka": "Apache Kafka",
    "apachespark": "Apache Spark",
    "apex": "Apex",
    "apl": "APL",
    "apollographql": "Apollo GraphQL",
    "appcelerator": "Appcelerator",
    "apple": "Apple",
    "appwrite": "Appwrite",
    "archlinux": "Arch Linux",
    "arduino": "Arduino",
    "argocd": "Argo CD",
    "artixlinux": "Artix Linux",
    "astro": "Astro",
    "atom": "Atom",
    "awk": "AWK",
    "axios": "Axios",
    "azure": "Azure",
    "azuredevops": "Azure DevOps",
    "azuresqldatabase": "Azure SQL Database",
    "babel": "Babel",
    "babylonjs": "Babylon.js",
    "backbonejs": "Backbone.js",
    "ballerina": "Ballerina",
    "bamboo": "Bamboo",
    "bash": "Bash",
    "bazel": "Bazel",
    "beats": "Beats",
    "behance": "Behance",
    "bevyengine": "Bevy Engine",
    "biome": "Biome",
    "bitbucket": "Bitbucket",
    "blazor": "Blazor",
    "blender": "Blender",
    "bootstrap": "Bootstrap",
    "bower": "Bower",
    "browserstack": "BrowserStack",
    "bulma": "Bulma",
    "bun": "Bun",
    "c": "C",
    "cairo": "Cairo",
    "cakephp": "CakePHP",
    "canva": "Canva",
    "capacitor": "Capacitor",
    "carbon": "Carbon",
    "cassandra": "Cassandra",
    "centos": "CentOS",
    "ceylon": "Ceylon",
    "chakraui": "Chakra UI",
    "chartjs": "Chart.js",
    "chrome": "Chrome",
    "circleci": "CircleCI",
    "clarity": "Clarity",
    "clickhouse": "ClickHouse",
    "clion": "CLion",
    "clojure": "Clojure",
    "clojurescript": "ClojureScript",
    "cloudflare": "Cloudflare",
    "cloudflareworkers": "Cloudflare Workers",
    "cloudrun": "Cloud Run",
    "cmake": "CMake",
    "cobol": "COBOL",
    "codeac": "Codeac",
    "codecov": "Codecov",
    "codeigniter": "CodeIgniter",
    "codepen": "CodePen",
    "coffeescript": "CoffeeScript",
    "composer": "Composer",
    "confluence": "Confluence",
    "consul": "Consul",
    "contao": "Contao",
    "corejs": "core-js",
    "cosmosdb": "Cosmos DB",
    "couchbase": "Couchbase",
    "couchdb": "CouchDB",
    "cpanel": "cPanel",
    "cplusplus": "C++",
    "crystal": "Crystal",
    "csharp": "C#",
    "css3": "CSS3",
    "cucumber": "Cucumber",
    "cypressio": "Cypress.io",
    "d3js": "D3.js",
    "dart": "Dart",
    "datadog": "Datadog",
    "datagrip": "DataGrip",
    "dataspell": "DataSpell",
    "datatables": "DataTables",
    "dbeaver": "DBeaver",
    "debian": "Debian",
    "delphi": "Delphi",
    "denojs": "Deno",
    "detaspace": "Deta Space",
    "devicon": "Devicon",
    "digitalocean": "DigitalOcean",
    "discloud": "Discloud",
    "discordjs": "Discord.js",
    "django": "Django",
    "djangorest": "Django REST",
    "docker": "Docker",
    "doctrine": "Doctrine",
    "dot-net": ".NET",
    "dotnetcore": ".NET Core",
    "dovecot": "Dovecot",
    "dreamweaver": "Dreamweaver",
    "dropwizard": "Dropwizard",
    "drupal": "Drupal",
    "duckdb": "DuckDB",
    "dyalog": "Dyalog",
    "dynamodb": "DynamoDB",
    "dynatrace": "Dynatrace",
    "eclipse": "Eclipse",
    "ecto": "Ecto",
    "elasticsearch": "Elasticsearch",
    "electron": "Electron",
    "eleventy": "Eleventy",
    "elixir": "Elixir",
    "elm": "Elm",
    "emacs": "Emacs",
    "embeddedc": "Embedded C",
    "ember": "Ember.js",
    "entityframeworkcore": "Entity Framework Core",
    "envoy": "Envoy",
    "erlang": "Erlang",
    "eslint": "ESLint",
    "expo": "Expo",
    "express": "Express",
    "facebook": "Facebook",
    "fastapi": "FastAPI",
    "fastify": "Fastify",
    "faunadb": "FaunaDB",
    "feathersjs": "Feathers",
    "fedora": "Fedora",
    "fiber": "Fiber",
    "figma": "Figma",
    "filamentphp": "Filament",
    "filezilla": "FileZilla",
    "firebase": "Firebase",
    "firebird": "Firebird",
    "firefox": "Firefox",
    "flask": "Flask",
    "flutter": "Flutter",
    "forgejo": "Forgejo",
    "fortran": "Fortran",
    "foundation": "Foundation",
    "framermotion": "Framer Motion",
    "framework7": "Framework7",
    "fsharp": "F#",
    "fusion": "Fusion",
    "gardener": "Gardener",
    "gatling": "Gatling",
    "gatsby": "Gatsby",
    "gazebo": "Gazebo",
    "gcc": "GCC",
    "gentoo": "Gentoo",
    "ghost": "Ghost",
    "gimp": "GIMP",
    "git": "Git",
    "gitbook": "GitBook",
    "github": "GitHub",
    "githubactions": "GitHub Actions",
    "githubcodespaces": "GitHub Codespaces",
    "gitkraken": "GitKraken",
    "gitlab": "GitLab",
    "gitpod": "Gitpod",
    "gitter": "Gitter",
    "gleam": "Gleam",
    "glitch": "Glitch",
    "go": "Go",
    "godot": "Godot",
    "goland": "GoLand",
    "google": "Google",
    "googlecloud": "Google Cloud",
    "googlecolab": "Google Colab",
    "gradle": "Gradle",
    "grafana": "Grafana",
    "grails": "Grails",
    "graphql": "GraphQL",
    "groovy": "Groovy",
    "grpc": "gRPC",
    "grunt": "Grunt",
    "gulp": "Gulp",
    "hadoop": "Hadoop",
    "handlebars": "Handlebars",
    "harbor": "Harbor",
    "hardhat": "Hardhat",
    "harvester": "Harvester",
    "haskell": "Haskell",
    "haxe": "Haxe",
    "helm": "Helm",
    "heroku": "Heroku",
    "hibernate": "Hibernate",
    "homebrew": "Homebrew",
    "hoppscotch": "Hoppscotch",
    "html5": "HTML5",
    "htmx": "htmx",
    "hugo": "Hugo",
    "hyperv": "Hyper-V",
    "ie10": "IE10",
    "ifttt": "IFTTT",
    "illustrator": "Illustrator",
    "inertiajs": "Inertia.js",
    "influxdb": "InfluxDB",
    "inkscape": "Inkscape",
    "insomnia": "Insomnia",
    "intellij": "IntelliJ IDEA",
    "ionic": "Ionic",
    "jaegertracing": "Jaeger",
    "jamstack": "Jamstack",
    "jasmine": "Jasmine",
    "java": "Java",
    "javascript": "JavaScript",
    "jeet": "Jeet",
    "jekyll": "Jekyll",
    "jenkins": "Jenkins",
    "jest": "Jest",
    "jetbrains": "JetBrains",
    "jetpackcompose": "Jetpack Compose",
    "jhipster": "JHipster",
    "jira": "Jira",
    "jiraalign": "Jira Align",
    "jquery": "jQuery",
    "json": "JSON",
    "jule": "Jule",
    "julia": "Julia",
    "junit": "JUnit",
    "jupyter": "Jupyter",
    "k3os": "K3os",
    "k3s": "K3s",
    "k6": "k6",
    "kaggle": "Kaggle",
    "kaldi": "Kaldi",
    "kalilinux": "Kali Linux",
    "karatelabs": "Karate",
    "karma": "Karma",
    "kdeneon": "KDE neon",
    "keras": "Keras",
    "kibana": "Kibana",
    "knexjs": "Knex.js",
    "knockout": "Knockout",
    "kotlin": "Kotlin",
    "krakenjs": "Kraken.js",
    "ktor": "Ktor",
    "kubeflow": "Kubeflow",
    "kubernetes": "Kubernetes",
    "labview": "LabVIEW",
    "laminas": "Laminas",
    "laravel": "Laravel",
    "laraveljetstream": "Laravel Jetstream",
    "latex": "LaTeX",
    "leetcode": "LeetCode",
    "less": "Less",
    "libgdx": "libGDX",
    "linkedin": "LinkedIn",
    "linux": "Linux",
    "linuxmint": "Linux Mint",
    "liquibase": "Liquibase",
    "livewire": "Livewire",
    "llvm": "LLVM",
    "lodash": "Lodash",
    "logstash": "Logstash",
    "love2d": "LÖVE",
    "lua": "Lua",
    "lumen": "Lumen",
    "magento": "Magento",
    "mapbox": "Mapbox",
    "mariadb": "MariaDB",
    "markdown": "Markdown",
    "materializecss": "Materialize",
    "materialui": "Material-UI",
    "matlab": "MATLAB",
    "matplotlib": "Matplotlib",
    "mattermost": "Mattermost",
    "maven": "Maven",
    "maya": "Maya",
    "memcached": "Memcached",
    "mercurial": "Mercurial",
    "meteor": "Meteor",
    "microsoftsqlserver": "Microsoft SQL Server",
    "minitab": "Minitab",
    "mithril": "Mithril",
    "mobx": "MobX",
    "mocha": "Mocha",
    "modx": "MODX",
    "moleculer": "Moleculer",
    "mongodb": "MongoDB",
    "mongoose": "Mongoose",
    "monogame": "MonoGame",
    "moodle": "Moodle",
    "msdos": "MS-DOS",
    "mysql": "MySQL",
    "nano": "Nano",
    "nats": "NATS",
    "neo4j": "Neo4j",
    "neovim": "Neovim",
    "nestjs": "NestJS",
    "netbeans": "NetBeans",
    "netbox": "NetBox",
    "netlify": "Netlify",
    "networkx": "NetworkX",
    "newrelic": "New Relic",
    "nextjs": "Next.js",
    "nginx": "NGINX",
    "ngrok": "ngrok",
    "ngrx": "NgRx",
    "nhibernate": "NHibernate",
    "nim": "Nim",
    "nimble": "Nimble",
    "nixos": "NixOS",
    "nodejs": "Node.js",
    "nodemon": "Nodemon",
    "nodered": "Node-RED",
    "nodewebkit": "NW.js",
    "nomad": "Nomad",
    "norg": "Norg",
    "notion": "Notion",
    "npm": "npm",
    "npss": "NPSS",
    "nuget": "NuGet",
    "numpy": "NumPy",
    "nuxt": "Nuxt",
    "nuxtjs": "Nuxt.js",
    "oauth": "OAuth",
    "objectivec": "Objective-C",
    "ocaml": "OCaml",
    "ohmyzsh": "Oh My Zsh",
    "okta": "Okta",
    "openal": "OpenAL",
    "openapi": "OpenAPI",
    "opencl": "OpenCL",
    "opencv": "OpenCV",
    "opengl": "OpenGL",
    "openstack": "OpenStack",
    "opensuse": "openSUSE",
    "opentelemetry": "OpenTelemetry",
    "opera": "Opera",
    "oracle": "Oracle",
    "ory": "Ory",
    "p5js": "p5.js",
    "packer": "Packer",
    "pandas": "Pandas",
    "passport": "Passport",
    "perl": "Perl",
    "pfsense": "pfSense",
    "phalcon": "Phalcon",
    "phoenix": "Phoenix",
    "photonengine": "Photon Engine",
    "photoshop": "Photoshop",
    "php": "PHP",
    "phpstorm": "PhpStorm",
    "pixijs": "PixiJS",
    "playwright": "Playwright",
    "plotly": "Plotly",
    "pm2": "PM2",
    "pnpm": "pnpm",
    "podman": "Podman",
    "poetry": "Poetry",
    "polygon": "Polygon",
    "portainer": "Portainer",
    "postcss": "PostCSS",
    "postgresql": "PostgreSQL",
    "postman": "Postman",
    "powershell": "PowerShell",
    "premierepro": "Premiere Pro",
    "primeng": "PrimeNG",
    "prisma": "Prisma",
    "processing": "Processing",
    "processwire": "ProcessWire",
    "prolog": "Prolog",
    "prometheus": "Prometheus",
    "protractor": "Protractor",
    "proxmox": "Proxmox",
    "pug": "Pug",
    "pulsar": "Pulsar",
    "pulumi": "Pulumi",
    "puppeteer": "Puppeteer",
    "purescript": "PureScript",
    "putty": "PuTTY",
    "pycharm": "PyCharm",
    "pypi": "PyPI",
    "pyscript": "PyScript",
    "pytest": "pytest",
    "python": "Python",
    "pytorch": "PyTorch",
    "qodana": "Qodana",
    "qt": "Qt",
    "qtest": "qTest",
    "quarkus": "Quarkus",
    "quasar": "Quasar",
    "qwik": "Qwik",
    "r": "R",
    "rabbitmq": "RabbitMQ",
    "racket": "Racket",
    "radstudio": "RAD Studio",
    "rails": "Rails",
    "railway": "Railway",
    "rancher": "Rancher",
    "raspberrypi": "Raspberry Pi",
    "reach": "Reach",
    "react": "React",
    "reactbootstrap": "React Bootstrap",
    "reactnative": "React Native",
    "reactnavigation": "React Navigation",
    "reactrouter": "React Router",
    "readthedocs": "Read the Docs",
    "realm": "Realm",
    "rect": "Rect",
    "redhat": "Red Hat",
    "redis": "Redis",
    "redux": "Redux",
    "reflex": "Reflex",
    "remix": "Remix",
    "renpy": "Ren'Py",
    "replit": "Replit",
    "rexx": "Rexx",
    "rider": "Rider",
    "rocksdb": "RocksDB",
    "rockylinux": "Rocky Linux",
    "rollup": "Rollup.js",
    "ros": "ROS",
    "rspec": "RSpec",
    "rstudio": "RStudio",
    "ruby": "Ruby",
    "rubymine": "RubyMine",
    "rust": "Rust",
    "rxjs": "RxJS",
    "safari": "Safari",
    "salesforce": "Salesforce",
    "sanity": "Sanity",
    "sass": "Sass",
    "scala": "Scala",
    "scalingo": "Scalingo",
    "scikitlearn": "scikit-learn",
    "sdl": "SDL",
    "selenium": "Selenium",
    "sema": "Sema",
    "sentry": "Sentry",
    "sequelize": "Sequelize",
    "shopware": "Shopware",
    "shotgrid": "ShotGrid",
    "sketch": "Sketch",
    "slack": "Slack",
    "socketio": "Socket.IO",
    "solidity": "Solidity",
    "solidjs": "SolidJS",
    "sonarqube": "SonarQube",
    "sourceengine": "Source Engine",
    "sourcetree": "Sourcetree",
    "spack": "Spack",
    "spicedb": "SpiceDB",
    "splunk": "Splunk",
    "spring": "Spring",
    "spss": "SPSS",
    "spyder": "Spyder",
    "sqlalchemy": "SQLAlchemy",
    "sqldeveloper": "SQL Developer",
    "sqlite": "SQLite",
    "ssh": "SSH",
    "stackblitz": "StackBlitz",
    "stackoverflow": "Stack Overflow",
    "stata": "Stata",
    "stenciljs": "Stencil",
    "storybook": "Storybook",
    "streamlit": "Streamlit",
    "styledcomponents": "styled-components",
    "stylus": "Stylus",
    "subversion": "Subversion",
    "sulu": "Sulu",
    "supabase": "Supabase",
    "surrealdb": "SurrealDB",
    "svelte": "Svelte",
    "svgo": "SVGO",
    "swagger": "Swagger",
    "swift": "Swift",
    "swiper": "Swiper",
    "symfony": "Symfony",
    "tailwindcss": "Tailwind CSS",
    "talos": "Talos",
    "tauri": "Tauri",
    "teleport": "Teleport",
    "tensorflow": "TensorFlow",
    "terraform": "Terraform",
    "terramate": "Terramate",
    "tex": "TeX",
    "thealgorithms": "The Algorithms",
    "threedsmax": "3ds Max",
    "threejs": "Three.js",
    "thymeleaf": "Thymeleaf",
    "titaniumsdk": "Titanium SDK",
    "tmux": "tmux",
    "tomcat": "Tomcat",
    "tortoisegit": "TortoiseGit",
    "towergit": "Tower",
    "traefikmesh": "Traefik Mesh",
    "traefikproxy": "Traefik Proxy",
    "travis": "Travis CI",
    "trello": "Trello",
    "trpc": "tRPC",
    "turbo": "Turbo",
    "twilio": "Twilio",
    "twitter": "Twitter",
    "typescript": "TypeScript",
    "typo3": "TYPO3",
    "ubuntu": "Ubuntu",
    "unifiedmodelinglanguage": "Unified Modeling Language",
    "unity": "Unity",
    "unix": "Unix",
    "unrealengine": "Unreal Engine",
    "uwsgi": "uWSGI",
    "v8": "V8",
    "vaadin": "Vaadin",
    "vagrant": "Vagrant",
    "vala": "Vala",
    "vault": "Vault",
    "veevalidate": "VeeValidate",
    "vercel": "Vercel",
    "vertx": "Vert.x",
    "vim": "Vim",
    "visualbasic": "Visual Basic",
    "visualstudio": "Visual Studio",
    "vite": "Vite",
    "vitejs": "Vite.js",
    "vitess": "Vitess",
    "vitest": "Vitest",
    "vscode": "Visual Studio Code",
    "vscodium": "VSCodium",
    "vsphere": "vSphere",
    "vuejs": "Vue.js",
    "vuestorefront": "Vue Storefront",
    "vuetify": "Vuetify",
    "vulkan": "Vulkan",
    "vyper": "Vyper",
    "waku": "Waku",
    "wasm": "WebAssembly",
    "web3js": "Web3.js",
    "webflow": "Webflow",
    "webgpu": "WebGPU",
    "weblate": "Weblate",
    "webpack": "webpack",
    "webstorm": "WebStorm",
    "windows11": "Windows 11",
    "windows8": "Windows 8",
    "wolfram": "Wolfram",
    "woocommerce": "WooCommerce",
    "wordpress": "WordPress",
    "xamarin": "Xamarin",
    "xcode": "Xcode",
    "xd": "Adobe XD",
    "xml": "XML",
    "yaml": "YAML",
    "yarn": "Yarn",
    "yii": "Yii",
    "yugabytedb": "YugabyteDB",
    "yunohost": "YunoHost",
    "zend": "Zend",
    "zig": "Zig",
    "zsh": "Zsh",
    "zustand": "Zustand"
}

#    名称到链接映射表
#    为特定图标的 <a> 标签指定自定义的 href 链接。如果未指定，默认为 "#"。
#    格式: "内部名称": "https://your-custom-link.com"
NAME_TO_LINK_MAP = {
    "aarch64": "https://en.wikipedia.org/wiki/AArch64",
    "adonisjs": "https://adonisjs.com",
    "aerospike": "https://www.aerospike.com",
    "aframe": "https://aframe.io",
    "aftereffects": "https://www.adobe.com/products/aftereffects.html",
    "akka": "https://akka.io",
    "algolia": "https://www.algolia.com",
    "almalinux": "https://almalinux.org",
    "alpinejs": "https://alpinejs.dev",
    "amazonwebservices": "https://aws.amazon.com",
    "anaconda": "https://www.anaconda.com",
    "android": "https://www.android.com",
    "androidstudio": "https://developer.android.com/studio",
    "angular": "https://angular.io",
    "angularjs": "https://angularjs.org",
    "angularmaterial": "https://material.angular.io",
    "ansible": "https://www.ansible.com",
    "ansys": "https://www.ansys.com",
    "antdesign": "https://ant.design",
    "apache": "https://www.apache.org",
    "apacheairflow": "https://airflow.apache.org",
    "apachekafka": "https://kafka.apache.org",
    "apachespark": "https://spark.apache.org",
    "apex": "https://apex.oracle.com",
    "apl": "https://en.wikipedia.org/wiki/APL_(programming_language)",
    "apollographql": "https://www.apollographql.com",
    "appcelerator": "https://www.appcelerator.com",
    "apple": "https://www.apple.com",
    "appwrite": "https://appwrite.io",
    "archlinux": "https://archlinux.org",
    "arduino": "https://www.arduino.cc",
    "argocd": "https://argo-cd.readthedocs.io",
    "artixlinux": "https://artixlinux.org",
    "astro": "https://astro.build",
    "atom": "https://github.com/atom/atom",
    "awk": "https://www.gnu.org/software/gawk/manual/gawk.html",
    "axios": "https://axios-http.com",
    "azure": "https://azure.microsoft.com",
    "azuredevops": "https://azure.microsoft.com/services/devops",
    "azuresqldatabase": "https://azure.microsoft.com/services/sql-database",
    "babel": "https://babeljs.io",
    "babylonjs": "https://www.babylonjs.com",
    "backbonejs": "https://backbonejs.org",
    "ballerina": "https://ballerina.io",
    "bamboo": "https://www.atlassian.com/software/bamboo",
    "bash": "https://www.gnu.org/software/bash",
    "bazel": "https://bazel.build",
    "beats": "https://www.elastic.co/beats",
    "behance": "https://www.behance.net",
    "bevyengine": "https://bevyengine.org",
    "biome": "https://biomejs.dev",
    "bitbucket": "https://bitbucket.org",
    "blazor": "https://dotnet.microsoft.com/apps/aspnet/web-apps/blazor",
    "blender": "https://www.blender.org",
    "bootstrap": "https://getbootstrap.com",
    "bower": "https://bower.io",
    "browserstack": "https://www.browserstack.com",
    "bulma": "https://bulma.io",
    "bun": "https://bun.sh",
    "c": "https://en.wikipedia.org/wiki/C_(programming_language)",
    "cairo": "https://www.cairographics.org",
    "cakephp": "https://cakephp.org",
    "canva": "https://www.canva.com",
    "capacitor": "https://capacitorjs.com",
    "carbon": "https://carbondesignsystem.com",
    "cassandra": "https://cassandra.apache.org",
    "centos": "https://www.centos.org",
    "ceylon": "https://ceylon-lang.org",
    "chakraui": "https://chakra-ui.com",
    "chartjs": "https://www.chartjs.org",
    "chrome": "https://www.google.com/chrome",
    "circleci": "https://circleci.com",
    "clarity": "https://clarity.design",
    "clickhouse": "https://clickhouse.com",
    "clion": "https://www.jetbrains.com/clion",
    "clojure": "https://clojure.org",
    "clojurescript": "https://clojurescript.org",
    "cloudflare": "https://www.cloudflare.com",
    "cloudflareworkers": "https://workers.cloudflare.com",
    "cloudrun": "https://cloud.google.com/run",
    "cmake": "https://cmake.org",
    "cobol": "https://en.wikipedia.org/wiki/COBOL",
    "codeac": "https://www.codeac.io",
    "codecov": "https://about.codecov.io",
    "codeigniter": "https://codeigniter.com",
    "codepen": "https://codepen.io",
    "coffeescript": "https://coffeescript.org",
    "composer": "https://getcomposer.org",
    "confluence": "https://www.atlassian.com/software/confluence",
    "consul": "https://www.consul.io",
    "contao": "https://contao.org",
    "corejs": "https://github.com/zloirock/core-js",
    "cosmosdb": "https://azure.microsoft.com/services/cosmos-db",
    "couchbase": "https://www.couchbase.com",
    "couchdb": "https://couchdb.apache.org",
    "cpanel": "https://cpanel.net",
    "cplusplus": "https://isocpp.org",
    "crystal": "https://crystal-lang.org",
    "csharp": "https://learn.microsoft.com/dotnet/csharp/",
    "css3": "https://developer.mozilla.org/en-US/docs/Web/CSS",
    "cucumber": "https://cucumber.io",
    "cypressio": "https://www.cypress.io",
    "d3js": "https://d3js.org",
    "dart": "https://dart.dev",
    "datadog": "https://www.datadoghq.com",
    "datagrip": "https://www.jetbrains.com/datagrip",
    "dataspell": "https://www.jetbrains.com/dataspell",
    "datatables": "https://datatables.net",
    "dbeaver": "https://dbeaver.io",
    "debian": "https://www.debian.org",
    "delphi": "https://www.embarcadero.com/products/delphi",
    "denojs": "https://deno.land",
    "detaspace": "https://deta.space",
    "devicon": "https://devicon.dev",
    "digitalocean": "https://www.digitalocean.com",
    "discloud": "https://discloud.app",
    "discordjs": "https://discord.js.org",
    "django": "https://www.djangoproject.com",
    "djangorest": "https://www.django-rest-framework.org",
    "docker": "https://www.docker.com",
    "doctrine": "https://www.doctrine-project.org",
    "dot-net": "https://dotnet.microsoft.com",
    "dotnetcore": "https://dotnet.microsoft.com",
    "dovecot": "https://www.dovecot.org",
    "dreamweaver": "https://www.adobe.com/products/dreamweaver.html",
    "dropwizard": "https://www.dropwizard.io",
    "drupal": "https://www.drupal.org",
    "duckdb": "https://duckdb.org",
    "dyalog": "https://www.dyalog.com",
    "dynamodb": "https://aws.amazon.com/dynamodb",
    "dynatrace": "https://www.dynatrace.com",
    "eclipse": "https://www.eclipse.org",
    "ecto": "https://hexdocs.pm/ecto/Ecto.html",
    "elasticsearch": "https://www.elastic.co/elasticsearch",
    "electron": "https://www.electronjs.org",
    "eleventy": "https://www.11ty.dev",
    "elixir": "https://elixir-lang.org",
    "elm": "https://elm-lang.org",
    "emacs": "https://www.gnu.org/software/emacs",
    "embeddedc": "https://en.wikipedia.org/wiki/Embedded_C",
    "ember": "https://emberjs.com",
    "entityframeworkcore": "https://learn.microsoft.com/en-us/ef/core/",
    "envoy": "https://www.envoyproxy.io",
    "erlang": "https://www.erlang.org",
    "eslint": "https://eslint.org",
    "expo": "https://expo.dev",
    "express": "https://expressjs.com",
    "facebook": "https://about.facebook.com",
    "fastapi": "https://fastapi.tiangolo.com",
    "fastify": "https://www.fastify.io",
    "faunadb": "https://fauna.com",
    "feathersjs": "https://feathersjs.com",
    "fedora": "https://getfedora.org",
    "fiber": "https://gofiber.io",
    "figma": "https://www.figma.com",
    "filamentphp": "https://filamentphp.com",
    "filezilla": "https://filezilla-project.org",
    "firebase": "https://firebase.google.com",
    "firebird": "https://firebirdsql.org",
    "firefox": "https://www.mozilla.org/firefox",
    "flask": "https://flask.palletsprojects.com",
    "flutter": "https://flutter.dev",
    "forgejo": "https://forgejo.org",
    "fortran": "https://fortran-lang.org",
    "foundation": "https://get.foundation",
    "framermotion": "https://www.framer.com/motion",
    "framework7": "https://framework7.io",
    "fsharp": "https://fsharp.org",
    "fusion": "#",
    "gardener": "https://gardener.cloud",
    "gatling": "https://gatling.io",
    "gatsby": "https://www.gatsbyjs.com",
    "gazebo": "https://gazebosim.org",
    "gcc": "https://gcc.gnu.org",
    "gentoo": "https://www.gentoo.org",
    "ghost": "https://ghost.org",
    "gimp": "https://www.gimp.org",
    "git": "https://git-scm.com",
    "gitbook": "https://www.gitbook.com",
    "github": "https://github.com",
    "githubactions": "https://github.com/features/actions",
    "githubcodespaces": "https://github.com/features/codespaces",
    "gitkraken": "https://www.gitkraken.com",
    "gitlab": "https://about.gitlab.com",
    "gitpod": "https://www.gitpod.io",
    "gitter": "https://gitter.im",
    "gleam": "https://gleam.run",
    "glitch": "https://glitch.com",
    "go": "https://go.dev",
    "godot": "https://godotengine.org",
    "goland": "https://www.jetbrains.com/go",
    "google": "https://www.google.com",
    "googlecloud": "https://cloud.google.com",
    "googlecolab": "https://colab.research.google.com",
    "gradle": "https://gradle.org",
    "grafana": "https://grafana.com",
    "grails": "https://grails.org",
    "graphql": "https://graphql.org",
    "groovy": "https://groovy-lang.org",
    "grpc": "https://grpc.io",
    "grunt": "https://gruntjs.com",
    "gulp": "https://gulpjs.com",
    "hadoop": "https://hadoop.apache.org",
    "handlebars": "https://handlebarsjs.com",
    "harbor": "https://goharbor.io",
    "hardhat": "https://hardhat.org",
    "harvester": "https://harvesterhci.io",
    "haskell": "https://www.haskell.org",
    "haxe": "https://haxe.org",
    "helm": "https://helm.sh",
    "heroku": "https://www.heroku.com",
    "hibernate": "https://hibernate.org",
    "homebrew": "https://brew.sh",
    "hoppscotch": "https://hoppscotch.io",
    "html5": "https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5",
    "htmx": "https://htmx.org",
    "hugo": "https://gohugo.io",
    "hyperv": "https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/about/",
    "ie10": "https://en.wikipedia.org/wiki/Internet_Explorer_10",
    "ifttt": "https://ifttt.com",
    "illustrator": "https://www.adobe.com/products/illustrator.html",
    "inertiajs": "https://inertiajs.com",
    "influxdb": "https://www.influxdata.com",
    "inkscape": "https://inkscape.org",
    "insomnia": "https://insomnia.rest",
    "intellij": "https://www.jetbrains.com/idea",
    "ionic": "https://ionicframework.com",
    "jaegertracing": "https://www.jaegertracing.io",
    "jamstack": "https://jamstack.org",
    "jasmine": "https://jasmine.github.io",
    "java": "https://www.java.com",
    "javascript": "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    "jeet": "http://jeet.gs",
    "jekyll": "https://jekyllrb.com",
    "jenkins": "https://www.jenkins.io",
    "jest": "https://jestjs.io",
    "jetbrains": "https://www.jetbrains.com",
    "jetpackcompose": "https://developer.android.com/jetpack/compose",
    "jhipster": "https://www.jhipster.tech",
    "jira": "https://www.atlassian.com/software/jira",
    "jiraalign": "https://www.atlassian.com/software/jira/align",
    "jquery": "https://jquery.com",
    "json": "https://www.json.org/json-en.html",
    "jule": "https://jule.dev",
    "julia": "https://julialang.org",
    "junit": "https://junit.org",
    "jupyter": "https://jupyter.org",
    "k3os": "https://k3os.io",
    "k3s": "https://k3s.io",
    "k6": "https://k6.io",
    "kaggle": "https://www.kaggle.com",
    "kaldi": "http://kaldi-asr.org",
    "kalilinux": "https://www.kali.org",
    "karatelabs": "https://github.com/karatelabs/karate",
    "karma": "http://karma-runner.github.io",
    "kdeneon": "https://neon.kde.org",
    "keras": "https://keras.io",
    "kibana": "https://www.elastic.co/kibana",
    "knexjs": "https://knexjs.org",
    "knockout": "https://knockoutjs.com",
    "kotlin": "https://kotlinlang.org",
    "krakenjs": "https://krakenjs.com",
    "ktor": "https://ktor.io",
    "kubeflow": "https://www.kubeflow.org",
    "kubernetes": "https://kubernetes.io",
    "labview": "https://www.ni.com/labview",
    "laminas": "https://getlaminas.org",
    "laravel": "https://laravel.com",
    "laraveljetstream": "https://jetstream.laravel.com",
    "latex": "https://www.latex-project.org",
    "leetcode": "https://leetcode.com",
    "less": "https://lesscss.org",
    "libgdx": "https://libgdx.com",
    "linkedin": "https://www.linkedin.com",
    "linux": "https://www.kernel.org",
    "linuxmint": "https://linuxmint.com",
    "liquibase": "https://www.liquibase.org",
    "livewire": "https://livewire.laravel.com",
    "llvm": "https://llvm.org",
    "lodash": "https://lodash.com",
    "logstash": "https://www.elastic.co/logstash",
    "love2d": "https://love2d.org",
    "lua": "https://www.lua.org",
    "lumen": "https://lumen.laravel.com",
    "magento": "https://business.adobe.com/products/magento/magento-commerce.html",
    "mapbox": "https://www.mapbox.com",
    "mariadb": "https://mariadb.org",
    "markdown": "https://daringfireball.net/projects/markdown",
    "materializecss": "https://materializecss.com",
    "materialui": "https://mui.com",
    "matlab": "https://www.mathworks.com/products/matlab.html",
    "matplotlib": "https://matplotlib.org",
    "mattermost": "https://mattermost.com",
    "maven": "https://maven.apache.org",
    "maya": "https://www.autodesk.com/products/maya",
    "memcached": "https://memcached.org",
    "mercurial": "https://www.mercurial-scm.org",
    "meteor": "https://www.meteor.com",
    "microsoftsqlserver": "https://www.microsoft.com/sql-server",
    "minitab": "https://www.minitab.com",
    "mithril": "https://mithril.js.org",
    "mobx": "https://mobx.js.org",
    "mocha": "https://mochajs.org",
    "modx": "https://modx.com",
    "moleculer": "https://moleculer.services",
    "mongodb": "https://www.mongodb.com",
    "mongoose": "https://mongoosejs.com",
    "monogame": "https://www.monogame.net",
    "moodle": "https://moodle.org",
    "msdos": "https://en.wikipedia.org/wiki/MS-DOS",
    "mysql": "https://www.mysql.com",
    "nano": "https://www.nano-editor.org",
    "nats": "https://nats.io",
    "neo4j": "https://neo4j.com",
    "neovim": "https://neovim.io",
    "nestjs": "https://nestjs.com",
    "netbeans": "https://netbeans.apache.org",
    "netbox": "https://netbox.dev",
    "netlify": "https://www.netlify.com",
    "networkx": "https://networkx.org",
    "newrelic": "https://newrelic.com",
    "nextjs": "https://nextjs.org",
    "nginx": "https://nginx.org",
    "ngrok": "https://ngrok.com",
    "ngrx": "https://ngrx.io",
    "nhibernate": "https://nhibernate.info",
    "nim": "https://nim-lang.org",
    "nimble": "https://github.com/nim-lang/nimble",
    "nixos": "https://nixos.org",
    "nodejs": "https://nodejs.org",
    "nodemon": "https://nodemon.io",
    "nodered": "https://nodered.org",
    "nodewebkit": "https://nwjs.io",
    "nomad": "https://www.nomadproject.io",
    "norg": "https://github.com/nvim-neorg/norg-specs",
    "notion": "https://www.notion.so",
    "npm": "https://www.npmjs.com",
    "npss": "#",
    "nuget": "https://www.nuget.org",
    "numpy": "https://numpy.org",
    "nuxt": "https://nuxt.com",
    "nuxtjs": "https://nuxtjs.org",
    "oauth": "https://oauth.net",
    "objectivec": "https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/Introduction/Introduction.html",
    "ocaml": "https://ocaml.org",
    "ohmyzsh": "https://ohmyz.sh",
    "okta": "https://www.okta.com",
    "openal": "https://www.openal.org",
    "openapi": "https://www.openapis.org",
    "opencl": "https://www.khronos.org/opencl/",
    "opencv": "https://opencv.org",
    "opengl": "https://www.opengl.org",
    "openstack": "https://www.openstack.org",
    "opensuse": "https://www.opensuse.org",
    "opentelemetry": "https://opentelemetry.io",
    "opera": "https://www.opera.com",
    "oracle": "https://www.oracle.com",
    "ory": "https://ory.sh",
    "p5js": "https://p5js.org",
    "packer": "https://www.packer.io",
    "pandas": "https://pandas.pydata.org",
    "passport": "https://www.passportjs.org",
    "perl": "https://www.perl.org",
    "pfsense": "https://www.pfsense.org",
    "phalcon": "https://phalcon.io",
    "phoenix": "https://www.phoenixframework.org",
    "photonengine": "https://www.photonengine.com",
    "photoshop": "https://www.adobe.com/products/photoshop.html",
    "php": "https://www.php.net",
    "phpstorm": "https://www.jetbrains.com/phpstorm",
    "pixijs": "https://pixijs.com",
    "playwright": "https://playwright.dev",
    "plotly": "https://plotly.com",
    "pm2": "https://pm2.keymetrics.io",
    "pnpm": "https://pnpm.io",
    "podman": "https://podman.io",
    "poetry": "https://python-poetry.org",
    "polygon": "https://polygon.technology",
    "portainer": "https://www.portainer.io",
    "postcss": "https://postcss.org",
    "postgresql": "https://www.postgresql.org",
    "postman": "https://www.postman.com",
    "powershell": "https://learn.microsoft.com/powershell",
    "premierepro": "https://www.adobe.com/products/premiere.html",
    "primeng": "https://primeng.org",
    "prisma": "https://www.prisma.io",
    "processing": "https://processing.org",
    "processwire": "https://processwire.com",
    "prolog": "https://en.wikipedia.org/wiki/Prolog",
    "prometheus": "https://prometheus.io",
    "protractor": "https://www.protractortest.org",
    "proxmox": "https://www.proxmox.com",
    "pug": "https://pugjs.org",
    "pulsar": "https://pulsar.apache.org",
    "pulumi": "https://www.pulumi.com",
    "puppeteer": "https://pptr.dev",
    "purescript": "https://www.purescript.org",
    "putty": "https://www.putty.org",
    "pycharm": "https://www.jetbrains.com/pycharm",
    "pypi": "https://pypi.org",
    "pyscript": "https://pyscript.net",
    "pytest": "https://pytest.org",
    "python": "https://www.python.org",
    "pytorch": "https://pytorch.org",
    "qodana": "https://www.jetbrains.com/qodana",
    "qt": "https://www.qt.io",
    "qtest": "https://www.tricentis.com/products/qtest",
    "quarkus": "https://quarkus.io",
    "quasar": "https://quasar.dev",
    "qwik": "https://qwik.builder.io",
    "r": "https://www.r-project.org",
    "rabbitmq": "https://www.rabbitmq.com",
    "racket": "https://racket-lang.org",
    "radstudio": "https://www.embarcadero.com/products/rad-studio",
    "rails": "https://rubyonrails.org",
    "railway": "https://railway.app",
    "rancher": "https://www.rancher.com",
    "raspberrypi": "https://www.raspberrypi.org",
    "reach": "https://reach.tech",
    "react": "https://react.dev",
    "reactbootstrap": "https://react-bootstrap.github.io",
    "reactnative": "https://reactnative.dev",
    "reactnavigation": "https://reactnavigation.org",
    "reactrouter": "https://reactrouter.com",
    "readthedocs": "https://readthedocs.org",
    "realm": "https://realm.io",
    "rect": "https://rect.dev",
    "redhat": "https://www.redhat.com",
    "redis": "https://redis.io",
    "redux": "https://redux.js.org",
    "reflex": "https://reflex.dev",
    "remix": "https://remix.run",
    "renpy": "https://www.renpy.org",
    "replit": "https://replit.com",
    "rexx": "https://en.wikipedia.org/wiki/Rexx",
    "rider": "https://www.jetbrains.com/rider",
    "rocksdb": "https://rocksdb.org",
    "rockylinux": "https://rockylinux.org",
    "rollup": "https://rollupjs.org",
    "ros": "https://www.ros.org",
    "rspec": "https://rspec.info",
    "rstudio": "https://posit.co/products/open-source/rstudio/",
    "ruby": "https://www.ruby-lang.org",
    "rubymine": "https://www.jetbrains.com/ruby",
    "rust": "https://www.rust-lang.org",
    "rxjs": "https://rxjs.dev",
    "safari": "https://www.apple.com/safari",
    "salesforce": "https://www.salesforce.com",
    "sanity": "https://www.sanity.io",
    "sass": "https://sass-lang.com",
    "scala": "https://www.scala-lang.org",
    "scalingo": "https://scalingo.com",
    "scikitlearn": "https://scikit-learn.org",
    "sdl": "https://www.libsdl.org",
    "selenium": "https://www.selenium.dev",
    "sema": "https://www.sema.so",
    "sentry": "https://sentry.io",
    "sequelize": "https://sequelize.org",
    "shopware": "https://www.shopware.com",
    "shotgrid": "https://www.autodesk.com/products/shotgrid",
    "sketch": "https://www.sketch.com",
    "slack": "https://slack.com",
    "socketio": "https://socket.io",
    "solidity": "https://soliditylang.org",
    "solidjs": "https://www.solidjs.com",
    "sonarqube": "https://www.sonarsource.com/products/sonarqube",
    "sourceengine": "https://developer.valvesoftware.com/wiki/Source",
    "sourcetree": "https://www.sourcetreeapp.com",
    "spack": "https://spack.io",
    "spicedb": "https://spicedb.dev",
    "splunk": "https://www.splunk.com",
    "spring": "https://spring.io",
    "spss": "https://www.ibm.com/spss",
    "spyder": "https://www.spyder-ide.org",
    "sqlalchemy": "https://www.sqlalchemy.org",
    "sqldeveloper": "https://www.oracle.com/database/sqldeveloper/",
    "sqlite": "https://www.sqlite.org",
    "ssh": "https://www.openssh.com",
    "stackblitz": "https://stackblitz.com",
    "stackoverflow": "https://stackoverflow.com",
    "stata": "https://www.stata.com",
    "stenciljs": "https://stenciljs.com",
    "storybook": "https://storybook.js.org",
    "streamlit": "https://streamlit.io",
    "styledcomponents": "https://styled-components.com",
    "stylus": "https://stylus-lang.com",
    "subversion": "https://subversion.apache.org",
    "sulu": "https://sulu.io",
    "supabase": "https://supabase.io",
    "surrealdb": "https://surrealdb.com",
    "svelte": "https://svelte.dev",
    "svgo": "https://github.com/svg/svgo",
    "swagger": "https://swagger.io",
    "swift": "https://www.swift.org",
    "swiper": "https://swiperjs.com",
    "symfony": "https://symfony.com",
    "tailwindcss": "https://tailwindcss.com",
    "talos": "https://www.talos.dev",
    "tauri": "https://tauri.app",
    "teleport": "https://goteleport.com",
    "tensorflow": "https://www.tensorflow.org",
    "terraform": "https://www.terraform.io",
    "terramate": "https://terramate.io",
    "tex": "https://www.tug.org/texlive/",
    "thealgorithms": "https://the-algorithms.com",
    "threedsmax": "https://www.autodesk.com/products/3ds-max",
    "threejs": "https://threejs.org",
    "thymeleaf": "https://www.thymeleaf.org",
    "titaniumsdk": "https://github.com/tidev/titanium-sdk",
    "tmux": "https://github.com/tmux/tmux/wiki",
    "tomcat": "https://tomcat.apache.org",
    "tortoisegit": "https://tortoisegit.org",
    "towergit": "https://www.git-tower.com",
    "traefikmesh": "https://traefik.io/traefik-mesh/",
    "traefikproxy": "https://traefik.io/traefik/",
    "travis": "https://www.travis-ci.com",
    "trello": "https://trello.com",
    "trpc": "https://trpc.io",
    "turbo": "https://turbo.build",
    "twilio": "https://www.twilio.com",
    "twitter": "https://twitter.com",
    "typescript": "https://www.typescriptlang.org",
    "typo3": "https://typo3.org",
    "ubuntu": "https://ubuntu.com",
    "unifiedmodelinglanguage": "https://www.uml.org",
    "unity": "https://unity.com",
    "unix": "https://en.wikipedia.org/wiki/Unix",
    "unrealengine": "https://www.unrealengine.com",
    "uwsgi": "https://uwsgi-docs.readthedocs.io",
    "v8": "https://v8.dev",
    "vaadin": "https://vaadin.com",
    "vagrant": "https://www.vagrantup.com",
    "vala": "https://wiki.gnome.org/Projects/Vala",
    "vault": "https://www.vaultproject.io",
    "veevalidate": "https://vee-validate.logaretm.com",
    "vercel": "https://vercel.com",
    "vertx": "https://vertx.io",
    "vim": "https://www.vim.org",
    "visualbasic": "https://learn.microsoft.com/dotnet/visual-basic/",
    "visualstudio": "https://visualstudio.microsoft.com",
    "vite": "https://vitejs.dev",
    "vitejs": "https://vitejs.dev",
    "vitess": "https://vitess.io",
    "vitest": "https://vitest.dev",
    "vscode": "https://code.visualstudio.com",
    "vscodium": "https://vscodium.com",
    "vsphere": "https://www.vmware.com/products/vsphere.html",
    "vuejs": "https://vuejs.org",
    "vuestorefront": "https://vuestorefront.io",
    "vuetify": "https://vuetifyjs.com",
    "vulkan": "https://www.vulkan.org",
    "vyper": "https://vyper.readthedocs.io",
    "waku": "https://waku.gg",
    "wasm": "https://webassembly.org",
    "web3js": "https://web3js.org",
    "webflow": "https://webflow.com",
    "webgpu": "https://www.w3.org/TR/webgpu/",
    "weblate": "https://weblate.org",
    "webpack": "https://webpack.js.org",
    "webstorm": "https://www.jetbrains.com/webstorm",
    "windows11": "https://www.microsoft.com/windows/windows-11",
    "windows8": "https://en.wikipedia.org/wiki/Windows_8",
    "wolfram": "https://www.wolfram.com",
    "woocommerce": "https://woocommerce.com",
    "wordpress": "https://wordpress.org",
    "xamarin": "https://dotnet.microsoft.com/apps/xamarin",
    "xcode": "https://developer.apple.com/xcode",
    "xd": "https://www.adobe.com/products/xd.html",
    "xml": "https://www.w3.org/XML/",
    "yaml": "https://yaml.org",
    "yarn": "https://yarnpkg.com",
    "yii": "https://www.yiiframework.com",
    "yugabytedb": "https://www.yugabyte.com",
    "yunohost": "https://yunohost.org",
    "zend": "https://www.zend.com",
    "zig": "https://ziglang.org",
    "zsh": "https://www.zsh.org",
    "zustand": "https://github.com/pmndrs/zustand"
}

# 输出文件名
OUTPUT_FILE = "output.md"

# 并发线程数
MAX_WORKERS = 20

API_URL = "https://api.github.com/repos/youzhiqingw/devicon/contents/icons"
print_lock = Lock() # 用于确保多线程打印不会混乱

def find_icon_url(session, name, display_name_map, link_map):
    """
    工作线程函数：查找图标URL，并收集详细的诊断日志。
    """
    log_messages = []
    
    # 检查自定义显示名称
    display_name = display_name_map.get(name)
    if display_name:
        log_messages.append(f"名称: 自定义显示名称 '{display_name}' 已应用。")
    else:
        display_name = name
        log_messages.append(f"名称: 未找到自定义显示名称，使用默认值 '{name}'。")

    # 检查自定义链接
    href = link_map.get(name)
    if href:
        log_messages.append(f"链接: 自定义链接 '{href}' 已应用。")
    else:
        href = "#"
        log_messages.append(f"链接: 未找到自定义链接，使用默认值 '#'。")

    # 查找图标SVG文件
    base_url = "https://raw.githubusercontent.com/youzhiqingw/devicon/master/icons/"
    suffixes = [
        "-original.svg", "-original-wordmark.svg",
        "-plain.svg", "-plain-wordmark.svg"
    ]
    
    found_svg_url = None
    icon_name_lower = name.lower()
    for suffix in suffixes:
        url = f"{base_url}{icon_name_lower}/{icon_name_lower}{suffix}"
        try:
            response = session.head(url, timeout=10)
            if response.status_code == 200:
                found_svg_url = url
                log_messages.append(f"图标: 成功找到SVG文件 -> {url}")
                break # 找到后立即退出循环
        except requests.RequestException:
            continue
    
    if not found_svg_url:
        log_messages.append("图标: [失败] 尝试所有后缀后，未找到有效的SVG文件。")
        return {"name": name, "status": "fail", "html": None, "log": log_messages}
    
    # 所有检查完成，生成HTML
    html_line = f'<a href="{href}" target="_blank" rel="noreferrer" title="{display_name}"><img src="{found_svg_url}" alt="{display_name}" width="40"/></a>'
    return {"name": name, "status": "success", "html": html_line, "log": log_messages}

def main():
    """
    主执行函数
    """
    print(f"正在从GitHub API获取图标列表: {API_URL}")
    try:
        headers = {"User-Agent": "Python-Icon-Script"}
        response = requests.get(API_URL, headers=headers, timeout=20)
        response.raise_for_status()
        all_items = response.json()
    except requests.exceptions.RequestException as e:
        print(f"错误: 请求GitHub API失败: {e}")
        return

    # 根据过滤器模式过滤项目
    dir_items = [item for item in all_items if item.get("type") == "dir"]
    
    if FILTER_MODE == 'whitelist':
        items_to_process = [item for item in dir_items if item.get("name") in FILTER_LIST]
        print(f"白名单模式激活。将只处理 FILTER_LIST 中的 {len(FILTER_LIST)} 个预设项目。")
    elif FILTER_MODE == 'blacklist':
        items_to_process = [item for item in dir_items if item.get("name") not in FILTER_LIST]
        print(f"黑名单模式激活。将处理所有项目，除了 FILTER_LIST 中的项目。")
    else:
        print(f"错误：无效的 FILTER_MODE '{FILTER_MODE}'。")
        return
        
    total_to_process = len(items_to_process)
    if total_to_process == 0:
        print("根据当前过滤规则，没有需要处理的项目。")
        return
        
    output_lines = []
    
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor, requests.Session() as session:
        futures = {
            executor.submit(find_icon_url, session, item.get("name"), NAME_TO_DISPLAY_NAME_MAP, NAME_TO_LINK_MAP): item 
            for item in items_to_process
        }
        
        print(f"开始并发处理 {total_to_process} 个图标...\n" + "-"*50)
        
        processed_count = 0
        for future in as_completed(futures):
            processed_count += 1
            result = future.result()
            name = result["name"]
            status = result["status"]
            
            # 使用锁来保证每个项目的报告作为一个整体被打印，不会被其他线程的输出打断
            with print_lock:
                status_tag = "[成功]" if status == "success" else "[失败]"
                print(f"{status_tag} [{processed_count}/{total_to_process}] 正在处理: {name}")
                for log_entry in result["log"]:
                    print(f"  - {log_entry}")
                print("-"*50)

            if status == "success":
                output_lines.append(result["html"])

    output_lines.sort(key=lambda html: html.split('title="')[1].split('"')[0].lower())

    try:
        with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
            f.write("\n".join(output_lines))
        
        print("\n" + "="*50)
        print("处理完成。")
        print(f"成功生成 {len(output_lines)} 条HTML记录。")
        print(f"结果已写入文件: {OUTPUT_FILE}")
        print(f"文件绝对路径: {os.path.abspath(OUTPUT_FILE)}")
        print("="*50)
    except IOError as e:
        print(f"\n错误：写入文件时发生异常: {e}")

if __name__ == "__main__":
    main()